# Generated by Django 2.2.3 on 2019-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=120, verbose_name='Ürün Adı')),
                ('birimFiyati', models.FloatField()),
                ('stokMiktari', models.IntegerField()),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
            ],
        ),
    ]
