# Generated by Django 2.2.3 on 2019-07-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatimFatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adedi', models.PositiveIntegerField()),
                ('aliciAdi', models.CharField(max_length=50)),
                ('tarihi', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SatimFaturaUrun', to='urun.Urun', verbose_name='Ürün')),
            ],
        ),
    ]
