# Generated by Django 2.2.3 on 2019-07-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calisan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calisan',
            old_name='resim',
            new_name='image',
        ),
    ]
