# Generated by Django 2.2.3 on 2019-07-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calisan', '0002_auto_20190722_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izin',
            name='izinTarihi',
            field=models.DateTimeField(),
        ),
    ]
