# Generated by Django 2.2.3 on 2019-07-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calisan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=120)),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('yoneticiCalisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonetici', to='calisan.Calisan', verbose_name='Yönetici')),
            ],
        ),
        migrations.CreateModel(
            name='Talep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Açıklama')),
                ('tarihi', models.DateTimeField(auto_now_add=True)),
                ('kabulDurumu', models.NullBooleanField(verbose_name='Kabul Durumu')),
                ('calisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TalepCalisan', to='calisan.Calisan', verbose_name='Çalışan')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TalepProje', to='proje.Proje', verbose_name='Proje')),
            ],
        ),
        migrations.CreateModel(
            name='EkipUye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EkipUyeCalisan', to='calisan.Calisan', verbose_name='Çalışan')),
                ('ekip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekip', to='proje.Ekip', verbose_name='Ekip')),
                ('yetki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EkipUyeYetki', to='calisan.Yetki', verbose_name='Yetki')),
            ],
        ),
        migrations.AddField(
            model_name='ekip',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EkipProje', to='proje.Proje', verbose_name='Proje'),
        ),
    ]
